"""Compose a pull-request comment from a review result (D2, D4).

Pure functions: no host, no filesystem. The only ``codehost`` symbol imported
is :class:`PullRequestRecord`, a frozen dataclass — the review package must
not learn the host's other shapes, the rule 383 established for persistence.
``tests/codehost/test_import_boundaries.py`` enforces this module as the one
exception to the review-package import ban.
"""

from __future__ import annotations

from squadron.codehost.models import PullRequestRecord
from squadron.review.models import ReviewResult, StructuredFinding

#: The only place the marker's shape is written.
MARKER_PREFIX = "<!-- squadron-review:"

#: GitHub rejects an issue comment body over 65536 characters. Findings are
#: truncated well under that so the omission line and the rest of the body
#: always fit alongside them.
_MAX_RENDERED_FINDINGS = 200

#: Severity display order: blocking findings first, so a PR reader meets them
#: before a note or a pass. Parse order is preserved within each group.
_SEVERITY_ORDER = ("fail", "concern", "note", "pass")


def marker_for(record: PullRequestRecord) -> str:
    """The hidden marker identifying a squadron review comment on ``record``.

    Built from :attr:`PullRequestRecord.key`, not ``path_key`` — there is no
    filesystem here, and the flattened form is only harder to read in comment
    source (D4).
    """
    return f"{MARKER_PREFIX} {record.key} -->"


def compose_comment(result: ReviewResult, record: PullRequestRecord, *, live_head_sha: str) -> str:
    """Render ``result`` as a PR comment body.

    Findings come from ``result.structured_findings``, not ``result.findings``
    — that projection assigns the same stable ids and lowercased severities
    the artifact's frontmatter carries, so the comment and the artifact cannot
    disagree about what was found (D2).
    """
    lines = [
        marker_for(record),
        f"## Squadron review — {result.verdict.value}",
        "",
        _model_line(result, record),
    ]
    staleness = _staleness_line(record.head_sha, live_head_sha)
    if staleness is not None:
        lines.append(staleness)
    lines += ["", "### Findings", ""]
    lines += _render_findings(result.structured_findings)
    lines += ["", "_Generated by squadron. Not a substitute for human review._"]
    return "\n".join(lines)


def _model_line(result: ReviewResult, record: PullRequestRecord) -> str:
    model = result.model or "unknown"
    reviewed = record.head_sha[:7] if record.head_sha else "unknown"
    return f"**Model:** `{model}` · **Reviewed:** `{reviewed}`"


def _staleness_line(reviewed_sha: str, live_head_sha: str) -> str | None:
    """The staleness statement, or ``None`` when the head has not moved (D7).

    A "current" line on every comment is noise that trains readers to skip the
    block where the warning will eventually appear, so a match renders nothing.
    """
    if reviewed_sha == live_head_sha:
        return None
    reviewed_short = reviewed_sha[:7] if reviewed_sha else "unknown"
    live_short = live_head_sha[:7] if live_head_sha else "unknown"
    return f"> **Stale:** reviewed `{reviewed_short}`, the pull request is now at `{live_short}`."


def _render_findings(findings: list[StructuredFinding]) -> list[str]:
    if not findings:
        return ["_No findings._"]

    grouped: dict[str, list[StructuredFinding]] = {severity: [] for severity in _SEVERITY_ORDER}
    for finding in findings:
        grouped.setdefault(finding.severity, []).append(finding)

    ordered: list[StructuredFinding] = []
    for severity in _SEVERITY_ORDER:
        ordered.extend(grouped.get(severity, []))
    # A severity outside the known set is rare but must not vanish silently.
    known = set(_SEVERITY_ORDER)
    for severity, items in grouped.items():
        if severity not in known:
            ordered.extend(items)

    shown = ordered[:_MAX_RENDERED_FINDINGS]
    omitted = len(ordered) - len(shown)

    lines = [_render_finding_line(finding) for finding in shown]
    if omitted > 0:
        lines.append("")
        lines.append(f"_{omitted} further findings omitted; see the full review._")
    return lines


def _render_finding_line(finding: StructuredFinding) -> str:
    summary = _neutralize_marker(finding.summary)
    line = f"- **[{finding.severity}]** `{finding.id}` {finding.category} — {summary}"
    if finding.location:
        line += f"\n  `{_neutralize_marker(finding.location)}`"
    return line


def _neutralize_marker(text: str) -> str:
    """Break any occurrence of the comment opener so composed content can
    never contain a second marker (D4).

    A zero-width space inside the opener defeats the substring match
    ``find_marked_comments`` performs, without altering how the text renders.
    """
    return text.replace("<!--", "<​!--")
